version: '3.4'

networks:
  netzon:
    driver: bridge

services:
  dockerapi:
    container_name: 'netzon-api'
    image: netzonapi:latest
    depends_on: 
      - 'postgres'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/aspnetcoreapp
    ports:
      - 8080:80
    environment:
      DB_CONNECTION_STRING: "host=postgres;port=5432;database=netzon-assessment-db;username=netzon;password=n3tz0n@123"
      JWT_SECRET: "jqQtDC5qZcnOqdFl2y4ef2VpHOCF3aMKWeR2faNr3ZbfM5T7n59iPZxPTV0gqNC1"
    networks:
      - netzon

  postgres:
    container_name: 'postgres'
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: netzon
      POSTGRES_PASSWORD: n3tz0n@123
      POSTGRES_DB: netzon-assessment-db
    networks:
      - netzon

      